### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by ivasugarg** [1ndianl33t/Gf-Patterns#9]
$ cat ~/oyosub.wb| gf ssrf | tee -a ssfrparams.txt             

fatal: 'ssrf' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I am not able to figure out as to why I am getting "fatal" error even after having carefully repeated all the steps several times.

**Comment by gh0sh** [comment]
Check your alias command, some system alias gf  command pointing to git command.

**Comment by ravkishu** [comment]
This is because might be using `oh-my-zsh` and related `~/.zshrc` has git plugin activated by default.
 - If you go to this git plugin, it has alias something like this
 - _This is the root cause of your problem_
 - https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh#L114
```zsh
alias gf='git fetch'
```

To overcome this issue just unalias this in your `~/.zshrc` file & then source it to make effective
```zsh
$ nano ~/.zshrc
unalias gf
$ source ~/.zshrc
```

It should solve your issue @ivasugarg
